### ISSUE TITLE
lots of changes and George added to DESCRIPTION

### ISSUE THREAD

**Issue by pachamaltese** [pachamaltese/d3plus#18]
Hi @jbkunst and @gvegayon 

You may know that Dave is here. He's not an R user but he created DataUSA and D3plus.

I made lots of changes that affect how easy is to create a geomap. Because of this I made `tibble` the default data structure to work with.

To begin with tonight's changes I added the product space from `oec` package. The network structure is ok, what's not ok is the grouping/colouring option.

For example you can run:

```
load(system.file("extdata", "product_space/hs92_4_usa_exports_2015.RData", package = "d3plus"))
load(system.file("extdata", "product_space/hs92_4_links.RData", package = "d3plus"))
load(system.file("extdata", "product_space/hs92_4_nodes.RData", package = "d3plus"))

hs92_4_usa_exports_2015 = hs92_4_usa_exports_2015 %>%
  inner_join(hs92_4_nodes) %>%
  select(id, val, color)

d3plus() %>%
  d3p_type("network") %>%
  d3p_data(hs92_4_usa_exports_2015) %>%
  d3p_nodes(hs92_4_nodes) %>%
  d3p_links(hs92_4_links) %>%
  d3p_colorscale("{fill: function(d) {return d.color;}}")
```

And this will write the network but assigning random colours. This is weird because I still need to find out a valid way to pass the `color` column from the data to D3plus 2.0. `oec` package uses D3plus 1.9 where lots of methods were different and in that package colours, groups and legends are ok.

I'd also like to pass custom colours to treemaps, so that you can do something like this:

```
dta4 <- tibble(parent = c(rep("Group 1",3), rep("Group 2",2)),
               id = c("alpha","beta","gamma","delta","eta"),
               col = c("#333333","yellow","#fafafa", "red","blue"),
               value = c(29,10,2,29,25))

d3plus() %>%
  d3p_type("treemap") %>%
  d3p_data(dta4) %>%
  d3p_groupby(c("parent","id")) %>%
  d3p_color("col")
```

I know you are great R programmers and I'm sure your contribution will make this package great !! I don't care if you love the tidyverse binaries or compile `data.table` on Arch, this is about the chicken and not the egg :)

**Comment by pachamaltese** [comment]
@gvegayon I just moved the data to data/

**Comment by gvegayon** [comment]
Cool
